### ISSUE TITLE
求助老师

### ISSUE THREAD

**Issue by uuleaf** [napoler/gpt2Write#5]
老师好，
不知道老师能在
https://github.com/Morizeyao/GPT2-Chinese/ 的基础上，加上 https://github.com/huggingface/transformers/tree/master/examples/pplm 可控文本生成的功能

我这边可以有偿 QQ2027725943

**Comment by napoler** [comment]
看样子很不错,好像和我们用 类别+文章 格式训练差不多也能实现可控文本的生成.
我也想要实现类似的效果毕竟让ai不可控的生成往往没啥意义,我之前都是想在训练格式上下功夫,比如:
关键词+文章
知识+文章
生成的内容也是类似的效果,我最喜欢的还是这种知识加上文章的格式.
这个即插即用倒是很不错,抽空有时间研究下

**Comment by napoler** [comment]
用albert加个判别器也差不多,恩可以的.
GPT2-Chinese和transformers区别就是换了bert的vocab吧
看了下修改这个https://github.com/huggingface/transformers/blob/master/examples/pplm/run_pplm_discrim_train.py文件
试试修改成这样子可以吗?
self.tokenizer = GPT2Tokenizer.from_pretrained(pretrained_model)
修改为
from tokenizations import tokenization_bert
self.tokenizer= tokenization_bert.BertTokenizer(vocab_file=args.tokenizer_path)
就可以吧,就可以拿训练好的中文模型用了吧
我没测试

**Comment by uuleaf** [comment]
非常感谢老师的提示
